### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Manliketjb** [qw-scripts/qw_skills#1]
Hello, getting 2 issues. skills not showing on the UI and a error in console
![Screenshot 2023-02-16 005326](https://user-images.githubusercontent.com/82594996/219229958-7fab08ff-c9dd-4593-8931-ad975863fb37.png)

**Comment by masonschafercodes** [comment]
please join discord for support: https://dsc.gg/qw-scripts

**Comment by Manliketjb** [comment]
i'm alright, just wanted to share the issue
